#ifndef INC_3DVIEWER_V2_0_SRC_VIEW_TYPE_TRANSFORM_H_
#define INC_3DVIEWER_V2_0_SRC_VIEW_TYPE_TRANSFORM_H_

enum TypeTransform { MOVE, SCALE, ROTATE };
enum Axis { X, Y, Z };

#endif  // INC_3DVIEWER_V2_0_SRC_VIEW_TYPE_TRANSFORM_H_
